- name: Copy rke2 agents config
  when: inventory_hostname in groups[rke2_agents_group_name]
  register: config_file_is_changed
  ansible.builtin.template:
    src: "{{ rke2_agent_config }}"
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: 0644


- name: Run RKE2 installation script
  environment:
    INSTALL_RKE2_VERSION: "{{ rke2_version }}"
    INSTALL_RKE2_CHANNEL_URL: "{{ rke2_channel_url }}"
    INSTALL_RKE2_CHANNEL: "{{ rke2_channel }}"
    INSTALL_RKE2_TYPE: "{{ rke2_installation_type }}"
  changed_when: false
  ansible.builtin.command:
    cmd: "{{ rke2_install_script_dir }}/rke2.sh"


- name: Start RKE2 agent service the remain hosts
  environment:
    RKE2_TOKEN: "{{ rke2_agent_token }}"
  ansible.builtin.systemd:
    name: "rke2-agent.service"
    state: started
    enabled: true