---

- name: Create the required directories 
  loop:
    - /etc/rancher
    - /etc/rancher/rke2
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
      

- name: Download RKE2 installation script
  ansible.builtin.get_url:
    url: "{{ rke2_install_url }}"
    dest: "{{ rke2_install_script_dir }}/rke2.sh"
    mode: 0700


